### ISSUE TITLE
Newest Docker image return "No implementation has been registered for service" with param --init-issuer

### ISSUE THREAD

**Issue by JonasZal** [walt-id/waltid-wallet-backend#9]
When selecting ebsi method to create Issuer DID registered on EBSI it returns:
Exception in thread "main" id.walt.servicematrix.exceptions.UnimplementedServiceException: No implementation has been registered for service: id.walt.services.essif.jsonrpc.JsonRpcService
        at id.walt.services.essif.jsonrpc.JsonRpcService.getImplementation(JsonRpcService.kt:87)
        at id.walt.services.essif.jsonrpc.JsonRpcService.execute$suspendImpl(JsonRpcService.kt:77)
        at id.walt.services.essif.jsonrpc.JsonRpcService.execute(JsonRpcService.kt)
        at id.walt.services.essif.didebsi.WaltIdDidEbsiService$registerDid$1.invokeSuspend(WaltIdDidEbsiService.kt:31)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:87)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:40)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at id.walt.services.essif.didebsi.WaltIdDidEbsiService.registerDid(WaltIdDidEbsiService.kt:25)
        at id.walt.services.essif.didebsi.DidEbsiService.registerDid(DidEbsiService.kt:11)
        at id.walt.issuer.backend.IssuerManager$initializeInteractively$1.invoke(IssuerManager.kt:138)
        at id.walt.issuer.backend.IssuerManager$initializeInteractively$1.invoke(IssuerManager.kt:130)
        at id.walt.services.context.WaltIdContextManager.runWith(ContextManager.kt:61)
        at id.walt.issuer.backend.IssuerManager.initializeInteractively(IssuerManager.kt:130)
        at id.walt.webwallet.backend.MainKt.main(Main.kt:39)

Here is my Bearer token:
eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE2Mzk0MDg5NTksImlhdCI6MTYzOTQwODA1OSwiaXNzIjoiZGlkOmVic2k6emNHdnFnWlRIQ3Rramd0Y0tSTDdIOGsiLCJvbmJvYXJkaW5nIjoiZXUtbG9naW4iLCJ2YWxpZGF0ZWRJbmZvIjp7InZhbGlkYXRlZFVzZXIiOnsiYXNzdXJhbmNlbGV2ZWwiOiIyMCIsImF1dGhlbnRpY2F0aW9uZmFjdG9ycyI6eyIkIjp7Im51bWJlciI6IjEifSwibW9uaWtlciI6ImpvbmFzLnphbGlua2V2aWNpdXNAZWRlbGl2ZXJ5Lmx0In0sImF1dGhlbnRpY2F0aW9ubGV2ZWwiOiJCQVNJQyIsImRvbWFpbiI6ImV4dGVybmFsIiwiZG9tYWludXNlcm5hbWUiOiJuMDAybmlhZSIsImVtYWlsIjoiam9uYXMuemFsaW5rZXZpY2l1c0BlZGVsaXZlcnkubHQiLCJlbXBsb3llZXR5cGUiOiJuIiwiZmlyc3RuYW1lIjoiSm9uYXMiLCJncm91cHMiOnsiJCI6eyJudW1iZXIiOiIwIn19LCJsYXN0bmFtZSI6IsW9YWxpbmtldmnEjWl1cyIsImxvY2FsZSI6ImVuIiwibG9naW5kYXRlIjoiMjAyMS0xMi0xM1QxNjowNzozNy4xODkrMDE6MDAiLCJzc28iOiJmYWxzZSIsInN0cmVuZ3RocyI6eyIkIjp7Im51bWJlciI6IjEifSwic3RyZW5ndGgiOiJTVFJPTkcifSwidGVsZXdvcmtpbmdwcmlvcml0eSI6ImZhbHNlIiwidGlja2V0dHlwZSI6IlNFUlZJQ0UiLCJ1aWQiOiJuMDAybmlhZSIsInVzZXIiOiJuMDAybmlhZSIsInVzZXJtYW5hZ2VyIjoidWlkPWtvbmRybWosb3U9UGVvcGxlLGRjPWNvbW1pc3Npb24sZGM9ZXVyb3BhLGRjPWV1In19fQ.vWMlCV2FKqfT1p0uvfmBkEKhTPAw0yWPUUppyrLRh2pnkw5qyjNZ2H4OKQuIwZsfZjvyxZDaZVwMfesTbvcE_g

**Comment by waltkb** [comment]
Hi Jonas!

As the error states, no implementation has been registered for the service: `id.walt.services.essif.jsonrpc.JsonRpcService`

If you don't have a custom implementation for this service, you can simply add the line
```id.walt.services.essif.jsonrpc.JsonRpcService=id.walt.services.essif.jsonrpc.WaltIdJsonRpcService```
to your `service-matrix.properties` and be good to go! (<-- WaltIdXYZService is always  the default service)

Otherwise, you can easily set your custom implementation after the equals sign (see https://github.com/walt-id/waltid-servicematrix)


Your bearer token is not needed for any issue and we will never ask for it (anyone asking for your bearer token is most likely a scammer, take care!).

Cheers!

**Comment by philpotisk** [comment]
Hi @JonasZal , I also have added the config that Kevin has mentioned to the default service-matrix file from the wallet-backend. please pull the latest code-base and run it again.
